-- TABLE USER INFO

-- TABLE 생성
CREATE TABLE USER_INFO(
    ID VARCHAR2(100),
    NAME VARCHAR2(300),
    NICKNM VARCHAR2(300),
    PASSWD VARCHAR2(300)
)

-- PRIMARY KEY 지정(ID)
ALTER TABLE USER_INFO 
ADD CONSTRAINT PK_ID PRIMARY KEY(ID);

-- TABLE 생성
CREATE TABLE COMMENT(
    ID VARCHAR2(100),
    TITLE VARCHAR2(100),
    COMMENT VARCHAR2(150),
    SCORE_C NUMBER(2,1)
)

-- FOREIGN KEY 지정(USER_INFO ID -> COMMENT ID)
ALTER TABLE COMMENT 
ADD CONSTRAINT FK_ID FOREIGN KEY(ID) 
REFERENCES COMMENT(ID);

COMMIT;