--Drop Table

DROP TABLE USER_INFO;
DROP TABLE commentary;
DROP TABLE media;
DROP TABLE webtoon;
DROP TABLE drama;
DROP TABLE Announcement;

-- Constraint 확인
SELECT * FROM USER_CONSTRAINTS;

-- USER_INFO table 생성
CREATE TABLE USER_INFO(
    u_num VARCHAR2(10),
    name VARCHAR2(300),
    nickNm VARCHAR2(300),
    passwd VARCHAR2(100),
    id VARCHAR2(100),
    ph_num VARCHAR2(50)
);

-- 주키 추가(u_num)
ALTER TABLE USER_INFO ADD CONSTRAINT PK_U_NUM PRIMARY KEY (U_NUM);

-- Sequence 생성
CREATE SEQUENCE SEQ_U_NUM
    START WITH 1 
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 데이터 생성시 자동으로 sequence 번호 넣어주는 TRIGGER
-- PL/SQL 활용
CREATE OR REPLACE TRIGGER TRG_U_NUM
BEFORE INSERT ON USER_INFO
FOR EACH ROW
BEGIN
    :NEW.u_num := SEQ_U_NUM.NEXTVAL;
END;

-- MEDIA table 생성
CREATE TABLE MEDIA( 
    m_num VARCHAR2(10),
    score NUMBER(4,2),
    opendate DATE,
    story VARCHAR2(3000),
    poster VARCHAR2(3000),
    highlight VARCHAR2(3000),
    title VARCHAR2(100)
);

-- 주키 추가(m_num)
ALTER TABLE MEDIA ADD CONSTRAINT PK_M_NUM PRIMARY KEY (M_NUM);

-- Sequence 생성
CREATE SEQUENCE SEQ_M_NUM
    START WITH 1 
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 데이터 생성시 자동으로 sequence 번호 넣어주는 TRIGGER
-- PL/SQL 활용
CREATE OR REPLACE TRIGGER TRG_M_NUM
BEFORE INSERT ON MEDIA
FOR EACH ROW
BEGIN
    :NEW.m_num := SEQ_M_NUM.NEXTVAL;
END;

-- WEBTOON table 생성
CREATE TABLE WEBTOON(
    w_num VARCHAR2(10),
    title VARCHAR2(200),
    thumbnail VARCHAR2(3000),
    synopsis VARCHAR2(3000),
    starScoreAverage NUMBER(4,2),
    readCount NUMBER(11),
    linkUrl VARCHAR2(50),
    writingAuthorName VARCHAR2(50)
);

-- 주키 추가(w_num)
ALTER TABLE WEBTOON ADD CONSTRAINT PK_W_NUM PRIMARY KEY (W_NUM);

-- Sequence 생성
CREATE SEQUENCE SEQ_W_NUM
    START WITH 1 
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 데이터 생성시 자동으로 sequence 번호 넣어주는 TRIGGER
-- PL/SQL 활용
CREATE OR REPLACE TRIGGER TRG_W_NUM
BEFORE INSERT ON WEBTOON
FOR EACH ROW
BEGIN
    :NEW.w_num := SEQ_W_NUM.NEXTVAL;
END;   

-- drama table 생성
CREATE TABLE DRAMA(
    d_num VARCHAR2(10),
    name VARCHAR2(200),
    overview VARCHAR2(3000),
    poster_path VARCHAR2(3000),
    first_air_date DATE
);

--주키 추가
ALTER TABLE DRAMA ADD CONSTRAINT PK_D_NUM PRIMARY KEY (D_NUM);

-- Sequence 생성
CREATE SEQUENCE SEQ_D_NUM
    START WITH 1 
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 데이터 생성시 자동으로 sequence 번호 넣어주는 TRIGGER
-- PL/SQL 활용
CREATE OR REPLACE TRIGGER TRG_D_NUM
BEFORE INSERT ON DRAMA
FOR EACH ROW
BEGIN
    :NEW.d_num := SEQ_D_NUM.NEXTVAL;
END; 

-- Commentary table 추가
CREATE TABLE COMMENTARY(
    c_num VARCHAR2(10),
    u_num VARCHAR2(10),
    m_num VARCHAR2(10),
    w_num VARCHAR2(10),
    d_num VARCHAR2(10),
    criticism VARCHAR2(150),
    score_c NUMBER(2,1),
    writedate DATE
)

--주키 추가(C_NUM)
ALTER TABLE COMMENTARY ADD CONSTRAINT PK_C_NUM PRIMARY KEY (C_NUM);

--외래키 추가(U_NUM, M_NUM, W_NUM, D_NUM)
ALTER TABLE COMMENTARY ADD CONSTRAINT FK_U_NUM FOREIGN KEY (U_NUM) 
REFERENCES USER_INFO(U_NUM) ON DELETE CASCADE;

ALTER TABLE COMMENTARY ADD CONSTRAINT FK_M_NUM FOREIGN KEY (M_NUM)
REFERENCES MEDIA(M_NUM) ON DELETE CASCADE;

ALTER TABLE COMMENTARY ADD CONSTRAINT FK_W_NUM FOREIGN KEY (W_NUM)
REFERENCES WEBTOON(W_NUM) ON DELETE CASCADE;

ALTER TABLE COMMENTARY ADD CONSTRAINT FK_D_NUM FOREIGN KEY (D_NUM)
REFERENCES DRAMA(D_NUM) ON DELETE CASCADE;

-- Sequence 생성
CREATE SEQUENCE SEQ_C_NUM
    START WITH 1 
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 데이터 생성시 자동으로 sequence 번호 넣어주는 TRIGGER
-- PL/SQL 활용
CREATE OR REPLACE TRIGGER TRG_C_NUM
BEFORE INSERT ON COMMENTARY
FOR EACH ROW
BEGIN
    :NEW.c_num := SEQ_C_NUM.NEXTVAL;
END; 

--Announcement table 추가
CREATE TABLE ANNOUNCEMENT(
    a_num VARCHAR2(10),
    a_title VARCHAR2(300),
    a_content VARCHAR2(3000),
    a_date DATE
);

--주키 추가
ALTER TABLE ANNOUNCEMENT ADD CONSTRAINT PK_A_NUM PRIMARY KEY (A_NUM);

-- Sequence 생성
CREATE SEQUENCE SEQ_A_NUM
    START WITH 1 
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 데이터 생성시 자동으로 sequence 번호 넣어주는 TRIGGER
-- PL/SQL 활용
CREATE OR REPLACE TRIGGER TRG_A_NUM
BEFORE INSERT ON ANNOUNCEMENT
FOR EACH ROW
BEGIN
    :NEW.a_num := SEQ_A_NUM.NEXTVAL;
END; 